version: '3'

services:
  redis3:
    image: "redis:3.2"
    command: redis-server
    ports:
      - "63793:6379"
    volumes:
      - $PWD/conf/redis3.conf:/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.3

  redis4:
    image: "redis:4.0-alpine"
    command: redis-server
    ports:
      - "63794:6379"
    volumes:
      - $PWD/conf/redis4.conf:/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4

  redis5:
    image: "redis:5.0"
    command: redis-server
    ports:
      - "63795:6379"
    volumes:
      - $PWD/conf/redis5.conf:/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.5

  redis6:
    image: "redis:6.0"
    command: redis-server
    ports:
      - "63796:6379"
    volumes:
      - $PWD/conf/redis6.conf:/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.6

  redis7:
    image: "redis:7.0"
    command: redis-server
    ports:
      - "63797:6379"
    volumes:
      - $PWD/conf/redis7.conf:/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.7

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
